export const AUTH_ENV = {
  AUTH_SECRET: 'AUTH_SECRET',
  AUTH_EXPIRATION_MILLS: 'AUTH_EXPIRATION_MILLS',
  AUTH_REFRESH_TOKEN_EXPIRATION_DAYS: 'AUTH_REFRESH_TOKEN_EXPIRATION_DAYS',
  AUTH_COOKIE_SAME_SITE: 'AUTH_COOKIE_SAME_SITE',
} as const;
