export const EMAIL_ENV = {
  EMAIL_GOOGLE_ID: 'EMAIL_GOOGLE_ID',
  EMAIL_GOOGLE_APP_PASSWORD: 'EMAIL_GOOGLE_APP_PASSWORD',
  EMAIL_RESET_PASSWD_REDIRECT_URL: 'EMAIL_RESET_PASSWD_REDIRECT_URL',
} as const;
